env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: ignore
  react/prop-types: 0 # TODO enable and add prop types
  "@typescript-eslint/explicit-module-boundary-types": off
  import/namespace: off # ignore errors in imported modules
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: route|index|_
  import/no-unresolved:
    - 2
    - ignore:
      - "@env" # this is used by react-native-dotenv
  "@typescript-eslint/no-namespace": "off"
  import/order:
    - 1
    - groups: [external, builtin, internal, sibling, parent, index]

overrides:
  - files: ["*.ts"] # don't check *.tsx files
    rules:
      "@typescript-eslint/explicit-module-boundary-types":
        - warn
