# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args:
          - "--maxkb=5000"
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        exclude: ^deployment
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: (^deployment/)|(package-lock\.json$)
        additional_dependencies:
          - prettier@3.1.0
          - "@trivago/prettier-plugin-sort-imports@^4.3.0"
  - repo: local
    hooks:
      - id: typescript
        name: typescript
        entry: |
          bash -c '
            ./node_modules/.bin/tsc --noEmit --outDir /tmp/tsc-output
          '
        language: system
        pass_filenames: false
        exclude: node_modules
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.3.0
    hooks:
      - id: eslint
        types: [file]
        files: ^.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        args: [--fix]
        additional_dependencies:
          - eslint@8.55.0
          - typescript@5.1.3
          - eslint-config-universe@12.0.0
